### ISSUE TITLE
missing quotes gives misleading error message

### ISSUE THREAD

**Issue by dckc** [pelletier/go-toml#413]
**Describe the bug**
The error message for missing quotes is misleading.

**To Reproduce**
1. put something like `timeout_broadcast_tx_commit = 20s`
2. start some utility that uses this library (such as cosmos-sdk)
3. `ERROR: While parsing config: (136, 33): parsing error: keys cannot contain new lines`

**Expected behavior**
`ERROR: While parsing config: (136, 33): parsing error: value requires quotes` or some such

**Versions**
 - go-toml: current, I think: 16c9a8b
 - go: go1.13.4.linux-amd64.tar.gz
 - operating system: Linux

**Comment by AllenX2018** [comment]
Thanks for reporting! I think it's a bug about the lexer when scanning integer type values

**Comment by dckc** [comment]
I wonder if it's specific to integer type values.

I got a similar error when quotes were missing from this line:

```
persistent_peers = 077c58e4b207d02bbbb1b68d6e7e1df08ce18a8a@178.62.245.23:26656,7d8550f6709e7ceaf170137fa6f950b50840185a@206.189.130.83:26656,25c93fb99654948f1f077b68ffa05feb85d909bb@138.197.185.203:26656,68e71ddd3801dc60c9a29afae28ea5bd0eddbe5c@134.209.176.58:26656,b0bdaf0e3eeb8078451ea274d16128f65610d682@138.68.63.241:26656,f6689f006fd3e1f27f1e7e83344f06198b47ee00@178.128.30.183:26656,30146727206eb81e796ccf837efa4b1f7235c221@165.227.33.200:26656
```

I'm not sure if the error message was the same. At some point while I was working on this, the error message was `ERROR: While parsing config: invalid base`.

But definitely in both cases, the solution was to add ""s around the value.

**Comment by bjanders** [comment]
It's not specific to integer types. I had:
```
host = builddb
```
and got the "keys cannot contain new line" error. This was corrected by correting my config:
```
host = "builddb"
```

**Comment by pelletier** [comment]
Looks like that's still not great in v2: https://play.golang.org/p/9xauDfRSQI7

```
1| host = builddb
 |        ~~~~~~~ incomplete number


1| persistent_peers = 077c58e4b207d02bbbb1b68d6e7e1df08ce18a8a@178.62.245.23:26656,7d8550f6709e7ceaf170137fa6f950b50840185a@206.189.130.83:26656,25c93fb99654948f1f077b68ffa05feb85d909bb@138.197.185.203:26656,68e71ddd3801dc60c9a29afae28ea5bd0eddbe5c@134.209.176.58:26656,b0bdaf0e3eeb8078451ea274d16128f65610d682@138.68.63.241:26656,f6689f006fd3e1f27f1e7e83344f06198b47ee00@178.128.30.183:26656,30146727206eb81e796ccf837efa4b1f7235c221@165.227.33.200:26656
 |                     ~ expected newline but got U+0037 '7'
```

cc @vincentserpoul, on the topic of providing more meaningful errors.

**Comment by pelletier** [comment]
Good insight on #858: maybe we should consider passing the type of the target to provide a more accurate error.
